apiVersion: v1
kind: Secret
metadata:
  name: beer-catalogue-db
  namespace: beer-catalogue
type: Opaque
stringData:
  SPRING_DATASOURCE_URL:
  SPRING_DATASOURCE_USERNAME:
  SPRING_DATASOURCE_PASSWORD:

